### ISSUE TITLE
Vanity url app: Folders will be marked as deleted instead of deleted directly like the vanity url nodes

### ISSUE THREAD

**Issue by majdhasan-aperto** [aperto/magnolia-vanity-url#21]
There are error messages, when you try to delete or publish as deleted marked folders.

**Comment by serialcool** [comment]
The easiest way is, to make the delete behaviour consistent between vanity url entries and folders. So it will be changed, that both works in the same following way:

1. confirm the deletion
2. delete node after confirmation

**Comment by serialcool** [comment]
Will be fixed in next release 1.5.4.

**Comment by serialcool** [comment]
Is also fixed with 1.6.0.
