### ISSUE TITLE
Optional description field

### ISSUE THREAD

**Issue by michael-evelt-lvm** [aperto/magnolia-vanity-url#27]
Hello again,

we would like to expand the usage of your app in our project and therefore it would be helpful to have an optional description field so that our editors can properly note, what this redirect is used for.
In the past we used our reverse-proxy for this task and repeatedly ran into the problem, that nobody could remember the original reason for the creation of specific redirect and if it could be deleted or not.

The changes would look as follows :
(the .txt extensions are added since yaml files are not allowed apperently)
src/main/resources/magnolia-vanity-url/apps/vanityUrls.yaml  (see section subApps.details.form.properties.description)
[apps_vanityUrls.yaml.txt](https://github.com/user-attachments/files/15971976/apps_vanityUrls.yaml.txt)

and for the contentType:
src/main/resources/magnolia-vanity-url/contentTypes/vanityUrl.yaml
[contentTypes_vanityUrls.yaml.txt](https://github.com/user-attachments/files/15971978/contentTypes_vanityUrls.yaml.txt)

I wanted to prepare a Pull-Request, but I do not have permission to push to your repository :-)

Thanks in advance and best regards
Michael Evelt

**Comment by michael-evelt-lvm** [comment]
[contentTypes_vanityUrls.yaml.txt](https://github.com/user-attachments/files/15971942/contentTypes_vanityUrls.yaml.txt)
[apps_vanityUrls.yaml.txt](https://github.com/user-attachments/files/15971953/apps_vanityUrls.yaml.txt)

It seems the original formatting did not work, I am sorry.
und also I cannot upload yaml files here. Therefore, I had to add the .txt extension...

**Comment by serialcool** [comment]
With version 1.6.4-SNAPSHOT and the following release the optional description field will be shown in the vanity url dialog. See commit in new project repository: https://github.com/IBM/magkit-vanity-url/commit/6ddce063456b1e747ae0fe0626cb25003c5d94bf

**Comment by michael-evelt-lvm** [comment]
Awesome, thank you very much :-) 
Could you inform me, once the new version is released?

**Comment by michael-evelt-lvm** [comment]
I just tested the Snapshot version and it works perfectly fine :-)

**Comment by serialcool** [comment]
Thx, for testing. I think it should be possible for me to create the release end of this week.

**Comment by michael-evelt-lvm** [comment]
Sounds great, thank you

**Comment by serialcool** [comment]
Included in release 1.6.4 of the magkit-vanity-url module.

https://github.com/IBM/magkit-vanity-url/releases/tag/magkit-vanity-url-1.6.4
