### ISSUE TITLE
dotall exclude blocks document redirects

### ISSUE THREAD

**Issue by michael-evelt-lvm** [aperto/magnolia-vanity-url#28]
Hello again,

I just ran into an "issue" with the excludes in the module definition. 
The `dotall` exclude https://github.com/IBM/magkit-vanity-url/blob/915364eeb4084c3e61f77c67b2e5c95c98461386/src/main/resources/mgnl-bootstrap/magkit-vanity-url/config.modules.magkit-vanity-url.config.excludes.xml#L7
prevents us from using multiple URLs representing a document, that supports a legacy link on our website:
/path/to/document.pdf  => some target
/service/old-stuff.jsp => some target

My main question is: 
Why is this excluded?
Because if it was to prevent overriding URLs like /.magnolia or /.rest the following regex would fulfill the same purpose, but would allow for the above mentioned examples:
`.*/\..*`

Maybe it would also be a good idea to update the validator in the app to contain this restriction. In the current situation the vanity url can be created, but it does not work.

Thanks in advance
Michael

**Comment by serialcool** [comment]
Hi, original this module was developed to provide just simple vanity urls for a Magnolia application, e.g. /wmas or /press. For this it was a good idea to exclude all urls containing a dot like page.html or document.pdf

But in some projects the vanity url module is used for enhanced urls also with a dot inside. In that case you can override or adapt the excludes in the module configuration by your own (update task, bootstrap and possible module decoration).

**Comment by michael-evelt-lvm** [comment]
Okay, great. Thank you!
I just wanted to be sure that I did not miss something.
Thanks for the clarification.
