### ISSUE TITLE
Support for Magnolia 6.3

### ISSUE THREAD

**Issue by ghost** [aperto/magnolia-vanity-url#29]
Hello!
I tested the vanityUrls App on Magnolia 6.3.0 and found some issues. Will there be a working version for 6.3?

The Issues I found are:

- Error message when saving a Entry (but the entry is still saved)
- There redirect is not executed

I didn't try to debug deeper on why these Errors happen...

**Comment by serialcool** [comment]
Hi, can you test with the latest version of this module from https://github.com/IBM/magkit-vanity-url? The project moved to a new Github space and there was a change in the maven coordinates. If these version also doesn't works, please open an issue in the new GitHub project space.

**Comment by ghost** [comment]
Yes, sorry. I already tested with the new VanityUrls version 1.6.4 and created a Issue on the new github repo here:

https://github.com/IBM/magkit-vanity-url/issues/16
